//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public string Client { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string TechName { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public int SensorID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Sensor Sensor { get; set; }
        public virtual User User { get; set; }
    }
}
